location = /easypic {
    return 308 /easypic/;
}

location ^~ /easypic/api/ {
    proxy_pass http://127.0.0.1:3010/api/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    client_max_body_size 1m;
}

location = /easypic/admin {
    return 308 /easypic/admin/;
}

location ^~ /easypic/admin/assets/ {
    root /var/www;
    try_files $uri =404;
    expires 1y;
    add_header Cache-Control "public, immutable";
}

location ^~ /easypic/admin/ {
    root /var/www;
    try_files $uri $uri/ /easypic/admin/index.html;
}

location ^~ /easypic/assets/ {
    root /var/www;
    try_files $uri =404;
    expires 1y;
    add_header Cache-Control "public, immutable";
}

location ^~ /easypic/ {
    root /var/www;
    try_files $uri $uri/ /easypic/index.html;
}
